spring:
  flyway:
    url: ${JDBC_DATASOURCE_URL}
  application:
    name: challenge
  servlet:
    multipart:
      max-request-size: 250MB
      max-file-size: 250MB
  datasource:
    driverClassName: org.postgresql.Driver
#    username: qgvhylpuinqsev
#    password: b952b9054da61ac24466da697de8f1616278396af237a2e470c923bd38573da3
#    url: jdbc:postgresql://ec2-18-210-214-86.compute-1.amazonaws.com:5432/d3o0ihrqeacnid?user=qgvhylpuinqsev&password=b952b9054da61ac24466da697de8f1616278396af237a2e470c923bd38573da3
    url: ${JDBC_DATASOURCE_URL}
    initialize-schema: always
  jpa:
    open-in-view: false
    show-sql: true
    generate-ddl: true
#    hibernate:
#      ddl-auto: update
#      sql: debug
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  jwt:
    secret: srsystemschallenge
